# application: pledgejs
# version: 1
runtime: python27
api_version: 1
threadsafe: true

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?\.libsvm$
- ^(.*/)?\.jar$
- .*\bIcon\b.*
- ^(.*/)?.*/old/.*$

handlers:
- url: /
  static_files: website/index.html
  upload: website/index\.html
  secure: always

- url: /(.*\.html)
  mime_type: text/html
  static_files: website/\1
  upload: website/(.*\.html)
  secure: always

- url: /css
  static_dir: website/css
  secure: always

- url: /favicon\.ico
  static_files: website/img/favicon.ico
  upload: website/img/favicon\.ico
  secure: always

- url: /js
  static_dir: website/js
  secure: always
  http_headers:
    Access-Control-Allow-Origin: "*"

- url: /img
  static_dir: website/img
  secure: always

- url: /README.md
  mime_type: text/markdown
  static_files: README.md
  upload: README.md
  secure: always

builtins:
- appstats: on

